#!/usr/bin/bash
source /usr/lib/ublue/setup-services/libsetup.sh
version-script flatpaks user 1 || exit 0

flatpak remote-add --user --if-not-exists flathub \
    https://flathub.org/repo/flathub.flatpakrepo

flatpak install -y --user flathub \
    org.mozilla.firefox \
    com.github.Eloston.UngoogledChromium \
    io.github.zen_browser.zen \
    com.discordapp.Discord \
    dev.vencord.Vesktop \
    dev.ferdium.Ferdium \
    com.spotify.Client \
    com.plexamp.Plexamp \
    org.videolan.VLC \
    tv.plex.PlexHTPC \
    com.github.iwalton3.jellyfin-media-player \
    md.obsidian.Obsidian \
    com.github.johnfactotum.Foliate \
    org.gnome.Loupe \
    org.gnome.Evince \
    org.gnome.clocks \
    com.github.wwmm.easyeffects \
    org.kde.kdeconnect \
    com.bitwarden.desktop \
    org.localsend.localsend_app \
    io.missioncenter.MissionCenter \
    com.github.tchx84.Flatseal \
    it.mijorus.gearlever \
    io.homeassistant.companion.linux \
    org.blender.Blender \
    org.kde.krita \
    com.ultimaker.cura \
    com.usebottles.bottles \
    com.jan.Jan \
    com.github.mtkennerly.ludusavi \
    org.mozilla.Thunderbird \
    net.heroicgameslauncher.hgl \
    net.lutris.Lutris \
    net.davidotek.pupgui2
